Project/routes/UserRoutes.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, flash, session ,jsonify
from services.UserService import UserService
from flask import render_template
from models.users import User
import logging
from extensions import db
import os
from itsdangerous import URLSafeTimedSerializer as Serializer

logger = logging.getLogger(__name__)
user_bp = Blueprint('user', __name__)

@user_bp.route('/', methods=['GET'])
def home():
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    else:
	    return render_template('dashboard.html')


@user_bp.route('/dashboard', methods=['GET'])
def dashboard():
    print("Current session:", session)
    print("Session get user_ID: ",session.get('user_id'))
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    else:
	    return render_template('dashboard.html')

@user_bp.route('/admin_dashboard', methods=['GET'])
def admin_dashboard():
    print("Current session:", session)
    print("Session get user_ID: ",session.get('user_id'))
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    else:
        return render_template('add_machine.html',addmachineClass='active',viewmachineClass='Not')

@user_bp.route('/add_machine', methods=['GET'])
def add_machine():
    print("Current session:", session)
    print("Session get user_ID: ",session.get('user_id'))
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    else:
        return render_template('add_machine.html',addmachineClass='active',viewmachineClass='Not')
    
@user_bp.route('/view_machine', methods=['GET'])
def view_machine():
    print("Current session:", session)
    print("Session get user_ID: ",session.get('user_id'))
    if 'user_id' not in session:
        return redirect(url_for('user.login'))
    else:
        return render_template('view_machine.html',addmachineClass='not',viewmachineClass='active')


@user_bp.route('/register', methods=['POST','GET'])
def register():
    logger.debug("UserRoutes.register endpoint called")
    if request.method == 'GET':
        return render_template('signup.html')
    try:
        firstname = request.form.get('firstname')   
        lastname = request.form.get('lastname')
        email = request.form.get('email')
        password = request.form.get('password')
        
        UserService.register_user(firstname, lastname, email, password)
        if request.method == 'POST':
            Uemail = request.form.get("email", False)
            print("User mail is", Uemail)
            # print("HTML Content:", HTML_CONTENT)
            reset_url = url_for('user.login', _external=True, _scheme='http')
            HTML_CONTENT = f'''
                        <html>
                        <head>
                            <title></title>
                            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                            <meta name="viewport" content="width=device-width, initial-scale=1">
                            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                            <style type="text/css">
                                /* FONTS */
                                @media screen {{
                                    @font-face {{
                                        font-family: 'Lato';
                                        font-style: normal;
                                        font-weight: 400;
                                        src: local('Lato Regular'), local('Lato-Regular'),
                                        url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');
                                    }}
                                    @font-face {{
                                        font-family: 'Lato';
                                        font-style: normal;
                                        font-weight: 700;
                                        src: local('Lato Bold'), local('Lato-Bold'),
                                        url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
                                    }}
                                    @font-face {{
                                        font-family: 'Lato';
                                        font-style: italic;
                                        font-weight: 400;
                                        src: local('Lato Italic'), local('Lato-Italic'),
                                        url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');
                                    }}
                                    @font-face {{
                                        font-family: 'Lato';
                                        font-style: italic;
                                        font-weight: 700;
                                        src: local('Lato Bold Italic'), local('Lato-BoldItalic'),
                                        url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');
                                    }}
                                }}
                                /* CLIENT-SPECIFIC STYLES */
                                body, table, td, a {{
                                    -webkit-text-size-adjust: 100%;
                                    -ms-text-size-adjust: 100%;
                                }}
                                table, td {{
                                    mso-table-lspace: 0pt;
                                    mso-table-rspace: 0pt;
                                }}
                                img {{
                                    -ms-interpolation-mode: bicubic;
                                }}
                                /* RESET STYLES */
                                img {{
                                    border: 0;
                                    height: auto;
                                    line-height: 100%;
                                    outline: none;
                                    text-decoration: none;
                                }}
                                table {{
                                    border-collapse: collapse !important;
                                }}
                                body {{
                                    height: 100% !important;
                                    margin: 0 !important;
                                    padding: 0 !important;
                                    width: 100% !important;
                                }}
                                /* iOS BLUE LINKS */
                                a[x-apple-data-detectors] {{
                                    color: inherit !important;
                                    text-decoration: none !important;
                                    font-size: inherit !important;
                                    font-family: inherit !important;
                                    font-weight: inherit !important;
                                    line-height: inherit !important;
                                }}
                                /* ANDROID CENTER FIX */
                                div[style*="margin: 16px 0;"] {{
                                    margin: 0 !important;
                                }}
                            </style>
                        </head>
                        <body style="background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;">
                            <div style="display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;">Hi!</div>
                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                <tbody>
                                    <tr>
                                        <td bgcolor="#C62B5B" align="center">
                                            <table border="0" cellpadding="0" cellspacing="0" width="480">
                                                <tbody>
                                                    <tr>
                                                        <td align="center" valign="top" style="padding: 40px 10px 40px 10px;">
                                                            <a href="https://pifs.lts.com.fj" target="_blank"></a>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td bgcolor="#C62B5B" align="center" style="padding: 0px 10px 0px 10px;">
                                            <table border="0" cellpadding="0" cellspacing="0" width="480">
                                                <tbody>
                                                    <tr>
                                                        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
                                                            <h1 style="font-size: 32px; font-weight: 400; margin: 0;">Is this you who have registered?</h1>
                                                        </td>
                                                    </tr>

Project/templates/add_machine.html
{% extends "admin_base.html" %}
{% block user_page %}  
              
      <div class="bg-white border-0 border-left px-3 py-2 rounded shadow-sm">
       <div class="text-dark">
              <h1 class="h3 text-primary">Add Machine</h1>
              <div class="row">
                  <div class="col-md-3">
                      <div class="py-2">
                          <div class="">
                              <img id="machine_icon" class="img-fluid" src="https://dl5hm3xr9o0pk.cloudfront.net/instagram/p-details-big.jpg">
                          </div>
                      </div>
                      <input type="file" class="py-3" id="machineImageUploader">
                  </div>
                  <div class="col-md-9">
                      <label class="mb-2">Machine Name *</label>
                      <input id="machine_name" class="form-control" type="text" required>
                      <label class="my-2">Machine Code *</label>
                      <input id="machine_code" class="form-control" type="text" readonly>
                      <label class="my-2">Machine Secret *</label>
                      <input id="machine_secret" class="form-control" type="password">
                      <label class="my-2">Machine Description</label>
                      <textarea id="machine_desc" draggable="false" class="form-control" rows="5"></textarea>
                  </div>
                  
              </div>
              <div class="mt-4 w-100">
                  <button class="btn btn-danger w-100" id="add_machine">Add machine</button>
              </div>
          </div>      
      </div>
      {% endblock %}   
       {% block javascript %}
       <script>
        $(document).ready(function() {
            function generateMachineCode() {
                let randomNum = Math.floor(1000 + Math.random() * 9000); // Generate a 4-digit random number
                return "CVBMIM" + randomNum; // Concatenate "MAC" with the random number
            }
    
            $("#machine_code").val(generateMachineCode()); // Set the generated code to the input field
        });
    </script>
       
      
      {% endblock %}

Project/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>User Dashboard</title>
        <link rel="stylesheet" href="../static/style.css">
        <link rel="icon" href="{{ url_for('static', filename='icon/favicon.ico') }}" type="image/x-icon">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.5/dist/sweetalert2.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
      
    

    </head>
    {% block stylesheets %}
    {% endblock %}
    <style>
        .h5, h5 {
    font-size: 1rem!important;
}

.logo {
    max-width: 100%;
    height: auto;
    max-height: 100px; /* Adjust the max height as needed */
}

.logo-wrapper {
    text-align: center;
}
    </style>

<body>
  <div class="loader-wrapper">
		<div class="loader"></div>
	</div>             
    <div class="container-fluid">
        <div class="row">
          <!-- sidebar -->
          <div class="col-md-3 col-lg-2 px-0 position-fixed h-100 bg-white shadow-sm sidebar" id="sidebar">
            <h1 class="logo-wrapper d-flex my-4 justify-content-center">
              <img src="static/images/logo2.png" alt="Logo" class="img-fluid logo">
          </h1>
          
            <div class="list-group rounded-0">
              <a href="{{ url_for('user.add_machine')}}" class="list-group-item {{addmachineClass}} list-group-item-action  border-0 d-flex align-items-center">
                <span class="bi bi-plus-circle-fill"></span>
                <span class="ml-2">Add Machine</span>
              </a>
              <a href="{{ url_for('user.view_machine')}}" class="list-group-item {{viewmachineClass}} list-group-item-action border-0 align-items-center">
                <span class="bi bi-view-list"></span>
                <span class="ml-2">View Machine</span>
              </a>
              
      
              <!-- <button class="list-group-item list-group-item-action border-0 d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#sale-collapse">
                <div>
                  <span class="bi bi-cart-dash"></span>
                  <span class="ml-2">Sales</span>
                </div>
                <span class="bi bi-chevron-down small"></span>
              </button> -->
              <!-- <div class="collapse" id="sale-collapse" data-parent="#sidebar">
                <div class="list-group">
                  <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Customers</a>
                  <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Sale Orders</a>
                </div>
              </div> -->
      
              <!-- <button class="list-group-item list-group-item-action border-0 d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#purchase-collapse">
                <div>
                  <span class="bi bi-cart-plus"></span>
                  <span class="ml-2">Purchase</span>
                </div>
                <span class="bi bi-chevron-down small"></span>
              </button> -->
              <!-- <div class="collapse" id="purchase-collapse" data-parent="#sidebar">
                <div class="list-group">
                  <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Sellers</a>
                  <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Purchase Orders</a>
                </div>
              </div> -->
            </div>
          </div>
          <!-- overlay to close sidebar on small screens -->
          <div class="w-100 vh-100 position-fixed overlay d-none" id="sidebar-overlay"></div>
          <!-- note: in the layout margin auto is the key as sidebar is fixed -->
          <div class="col-md-9 col-lg-10 ml-md-auto px-0">
            <!-- top nav -->
            <nav class="w-100 d-flex px-4 py-2 mb-4 shadow-sm">
              <!-- close sidebar -->
              <button class="btn py-0 d-lg-none" id="open-sidebar">
                <span class="bi bi-list text-primary h3"></span>
              </button>
              <div class="dropdown ml-auto">
                <button class="btn py-0 d-flex align-items-center" id="logout-dropdown" data-toggle="dropdown" aria-expanded="false">
                  <span class="bi bi-person text-primary h4"></span>
                  <span class="bi bi-chevron-down ml-1 mb-2 small"></span>
                </button>
                <div class="dropdown-menu dropdown-menu-right border-0 shadow-sm" aria-labelledby="logout-dropdown">
                  <a class="dropdown-item" href="/logout">Logout</a>
                  <a class="dropdown-item" href="#">Settings</a>
                </div>
              </div>
            </nav>
            <!-- main content -->
            <main class="container-fluid">
             
                {% block user_page %}


                {% endblock %}
              
            </main>
          </div>
        </div>
      </div>
    
    <!-- Button to trigger modal -->


<!-- Modal -->


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Load other scripts -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.5/dist/sweetalert2.all.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/admin_dashboard.js') }}"></script>

<!-- Custom scripts using jQuery -->
<script>
  $(document).ready(function() {
    // Toastr options
    toastr.options = {
      'closeButton': true,
      'debug': false,
      'newestOnTop': false,
      'progressBar': false,
      'positionClass': 'toast-top-right',
      'preventDuplicates': false,
      'showDuration': '1000',
      'hideDuration': '1000',
      'timeOut': '5000',
      'extendedTimeOut': '1000',
      'showEasing': 'swing',
      'hideEasing': 'linear',
      'showMethod': 'fadeIn',
      'hideMethod': 'fadeOut',
    };

    // Sidebar toggle
    $('#open-sidebar').click(function() {
      // Add class active on #sidebar
      $('#sidebar').addClass('active');
      // Show sidebar overlay
      $('#sidebar-overlay').removeClass('d-none');
    });

    $('#sidebar-overlay').click(function() {
      // Remove class active on #sidebar
      $('#sidebar').removeClass('active');
      // Hide sidebar overlay
      $(this).addClass('d-none');
    });
  });
</script>


{% block javascript %}
{% endblock %}
    
</body>
</html>

Project/templates/changepass.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login Page</title>
  <link rel="icon" href="static/images/myfavicon.ico" type="image/x-icon">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
  
</head>

<body class="vh-100">
  <div class="container-fluid p-0">
    <div class="m-0 row vh-100 w-100">
      <div class="bg-light col-lg-6 m-0 px-2 px-md-5">
        
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
          <div class="px-5 py-3">
            <div>
              <img class="bx bxl-c-plus-plus img-fluid " src="{{ url_for('static', filename='images/logo2.png') }} " style="max-width: 200px; height: auto;"> 
            </div>
          </div>
          {% if form %}
          <form class="form__content w-100 px-5" role="form" method="post" action="/changepass" id="login_form">
            <div class="form__content__header text-left">
                <h1 class="form__content__heading h2 mb-3">Reset Password !😎</h1>
                <div class="form__content__description">
                  Today is a new day. It's your day. You shape it. Sign in to start managing your projects.
                </div>
            </div>
            <div class="my-2">
                <label class="form__label" for="email">New Password</label>
                <input class="form-control"  id="password" type="password" name="password" placeholder="At least 8 characters" required>
            </div>
            <div class="my-2">
              <label class="form__label" for="email">Re Password</label>
              <input class="form-control" id="repassword" type="password" placeholder="At least 8 characters" name="repassword" required>
              <div class="input-icon-right peek-password-button" data-peek-password="signupInputPassword">
                <span class="peek-password-icon icon-visibility"></span>
              </div>
        
        
        
            <div class="password-strength-group pt-3" data-strength="">
        
              <div id="password-strength-meter" class="password-strength-meter">
                <div class="meter-block"></div>
                <div class="meter-block"></div>
                <div class="meter-block"></div>
                <div class="meter-block"></div>
              </div>
        
              <div class="password-strength-message">
                <div class="message-item">
                  Weak Password
                </div>
        
                <div class="message-item">
                  Okay
                </div>
        
                <div class="message-item">
                  Strong
                </div>
        
                <div class="message-item">
                  Very Strong!
                </div>
              </div>
            </div>
            </div>
            <div>
              {% with messages = get_flashed_messages(with_categories=true) %}
                  {% if messages %}
                      {% for category, message in messages %}
                          <div class="alert alert-{{ category }} mt-2">
                              <div class="errorMessage m-0">
                                  {{ message }}
                              </div>
                          </div>
                      {% endfor %}
                  {% endif %}
              {% endwith %}
          </div>
            <div class="my-3 form__submit">
                <button class="btn  w-100" type="submit">Reset Now!</button>
            </div>
            <div class="text-center"> Already have an account?<a href="{{ url_for('login') }}" class="mx-1">Sign in</a></div>
          </form>
          {% endif %}
          {% if changed %}
          <div class="p-4">
            <div style="display: inline-flex;text-align: center;" class="mb-2">
              <i class="fa fa-4x fa-check-square" style=" color: #005b00;"></i>
              <h2 class="h4">Password reset Successfully</h2>
          
            </div>
            <div>
              <div class="">
                <a class="backtologin btn useless" href="/login">Back To Login</a>
              </div>
            </div>
          </div>
          {% endif %}

          {% if unchanged %}
         <div class="p-4">
            <div style="display: inline-flex;text-align: center;" class="mb-2">
              <i class="fa fa-4x fa-check-square" style=" color: #005b00;"></i>
              <h2 class="h4">Password reset Unsuccessfully</h2>
          
            </div>
            <div>
              <div class="">
                <a class="backtologin btn useless" href="/login">Back To Login</a>
              </div>
            </div>
          </div>
            {% endif %}
        </div>
      </div>
      <div class="col-lg-6 d-lg-block d-none m-0" style="background: #dbdad9;">
        <div class="d-flex flex-column h-100 justify-content-center">
          <img src="{{ url_for('static', filename='images') }}/changePass.svg" alt="" class="" style="object-fit: contain;background-position: center;">
        </div>
      
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
  <script type="text/javascript">
    // Default Configuration
      $(document).ready(function() {
        toastr.options = {
          'closeButton': true,
          'debug': false,
          'newestOnTop': false,
          'progressBar': false,
          'positionClass': 'toast-top-right',
          'preventDuplicates': false,
          'showDuration': '1000',
          'hideDuration': '1000',
          'timeOut': '5000',
          'extendedTimeOut': '1000',
          'showEasing': 'swing',
          'hideEasing': 'linear',
          'showMethod': 'fadeIn',
          'hideMethod': 'fadeOut',
        }
      });
  
      
    </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    // Add JavaScript to check if both password fields are equal
    document.getElementById("login_form").addEventListener("submit", function(event) {
      var password = document.getElementById("password").value;
      var repassword = document.getElementById("repassword").value;
      
      if (password !== repassword) {
        toastr.error("Password Don't Match");
        event.preventDefault(); // Prevent the form from submitting
      }
    });
  </script>
  <script>
  
function passwordCheck(password) {
  if (password.length >= 8)
    strength += 1;
  if (password.match(/(?=.*[0-9])/))
    strength += 1;
  if (password.match(/(?=.*[!,%,&,@,#,$,^,*,?,_,~,<,>,])/))
    strength += 1;
  if (password.match(/(?=.*[a-z])/))
    strength += 1;

  displayBar(strength);
}

function displayBar(strength) {
  $(".password-strength-group").attr('data-strength', strength);
}
    
    $(document).on('keyup', '#password', function() {
  
      strength = 0;
      var password = $(this).val();
      passwordCheck(password);
    });
 
  </script>



</body>

</html>

Project/templates/dashboard.html
{% extends "base.html" %}
{% block user_page %}  
              <section class="row">
                <div class="col-md-6 col-lg-3">
                  <!-- card -->
                  <article class="p-4 rounded shadow-sm border-left
                     mb-4">
                    <div class="m-0 text-center">
                     <div class="icon-circle mb-3">
                                <i class="fa-solid fa-industry"></i>
                            </div>
                            <h5><strong>Total No. of Machines</strong></h5>
                            <div id="total-machines">
                              
                            </div>
                        </div>
                  </article>
                </div>
                <div class="col-md-6 col-lg-3">
                    <!-- card -->
                    <article class="p-4 rounded shadow-sm border-left
                       mb-4">
                       <div class="m-0 text-center">
                        <div class="icon-circle mb-3">
                            <i class="fa-solid fa-pills"></i>
                        </div>  
                        <h5><strong> No of Medicinal Strips </strong></h5>
                        <div id="total-strips">
                        </div>

                       </div>
                    </article>
                  </div>
                <div class="col-md-6 col-lg-3">
                  <article class="p-4 rounded shadow-sm border-left mb-4">
                    <div class="m-0 text-center">
                        <div class="icon-circle mb-3">
                            <i class="fa-solid fa-capsules text-danger"></i>
                        </div>
                        <h5><strong>No of Faulty Strips</strong></h5>
                        <p></p>
                        <div id='faulty-strips'>
                        </div>
                    </div>
                  </article>
                </div>
                <div class="col-md-6 col-lg-3">
                  <article class="p-4 rounded shadow-sm border-left mb-4">
                    <div class="m-0 text-center">
                    <div class="icon-circle mb-3">
                        <i class="fa-solid fa-prescription-bottle-medical text-success"></i>
                    </div>
                    <h5><strong>No of Non-Faulty Strips</strong></h5>
                    <p></p>

                            <div id='non-faulty-strips'>
                            
                            </div></div>
                  </article>
                </div>
              </section>
              
              <div class="bg-white border-0 border-left px-3 py-2 rounded shadow-sm">
                <div class="m-0 my-3 px-0 row">
                    <div class="col-6 p-0">
                        <div class="h5">Available Machines</div>
                    </div>
                    <div class="col-6 p-0 text-right">
                        <button class="btn btn-primary" aria-label="Add new machine" data-toggle="modal" data-target="#addMachineModal">
                            Link Machine <i class="fas fa-plus"></i>
                        </button>
                    </div>
                </div>
                <div class="w-100">
            
                <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>#</th>
                            <th>Machine Code</th>
                            <th>Created By</th>
                            <th>created_date</th>
                            <th>updated_date</th>
                            <th>Generate Report</th>
                            <th>De-Link</th>
                            </tr>
                    </thead>
                    <tbody id="machines-table-body"></tbody>
                </table>
            
            </div>
        </div>
      </div>
          
      {% endblock %}

Project/templates/layout.html
<!doctype html>
<title> Login Page </title>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% block body %}{% endblock %}